---
services:
  database:
    image: "valle/zulip-postgresql:14-valle.1"
    pull_policy: never
    container_name: valle-zulip-db
    mem_limit: 768m
    cpus: "0.50"
    pids_limit: 128

  memcached:
    image: "memcached:1.6-alpine"
    pull_policy: never
    container_name: valle-zulip-memcached
    mem_limit: 128m
    cpus: "0.25"
    pids_limit: 64

  rabbitmq:
    image: "rabbitmq:4.2-alpine"
    pull_policy: never
    container_name: valle-zulip-rabbitmq
    mem_limit: 256m
    cpus: "0.50"
    pids_limit: 192

  redis:
    image: "redis:8.2-alpine"
    pull_policy: never
    container_name: valle-zulip-redis
    mem_limit: 256m
    cpus: "0.25"
    pids_limit: 64

  zulip:
    image: "valle/zulip-server:12.2-valle.1"
    pull_policy: never
    container_name: valle-zulip
    build:
      args:
        ZULIP_GIT_URL: "https://github.com/MatheusMaior/valle-zulip.git"
        ZULIP_GIT_REF: "8a58bd672622224a5eb09bb717326debfaed60f0"
    ports: !reset []
    expose: ["80"]
    environment:
      SETTING_EXTERNAL_HOST: "chat.vallemonterei.com.br"
      SETTING_ZULIP_ADMINISTRATOR: "chat-admin@vallemonterei.com.br"
      SETTING_ENABLE_GRAVATAR: "False"
      SETTING_INLINE_URL_EMBED_PREVIEW: "False"
      SETTING_SEND_LOGIN_EMAILS: "False"
      SETTING_ZULIP_SERVICE_PUSH_NOTIFICATIONS: "False"
      SETTING_ZULIP_SERVICE_SUBMIT_USAGE_STATISTICS: "False"
      SETTING_ZULIP_SERVICE_SECURITY_ALERTS: "False"
      SETTING_SUBMIT_USAGE_STATISTICS: "False"
      SETTING_PROMOTE_SPONSORING_ZULIP: "False"
      SETTING_TUTORIAL_ENABLED: "False"
      LOADBALANCER_IPS: "172.18.0.0/16"
      TRUST_GATEWAY_IP: "True"
      ZULIP_AUTH_BACKENDS: "EmailAuthBackend"
      ZULIP_CUSTOM_SETTINGS: |
        JWT_AUTH_KEYS = {
            "": {
                "key": get_secret("jwt_auth_key"),
                "algorithms": ["HS256"],
            },
        }
    secrets:
      - zulip__jwt_auth_key
    networks:
      - default
      - supabase_default
    mem_limit: 2g
    cpus: "1.00"
    pids_limit: 512

secrets:
  zulip__postgres_password:
    environment: "ZULIP__POSTGRES_PASSWORD"
  zulip__memcached_password:
    environment: "ZULIP__MEMCACHED_PASSWORD"
  zulip__rabbitmq_password:
    environment: "ZULIP__RABBITMQ_PASSWORD"
  zulip__redis_password:
    environment: "ZULIP__REDIS_PASSWORD"
  zulip__secret_key:
    environment: "ZULIP__SECRET_KEY"
  zulip__email_password:
    environment: "ZULIP__EMAIL_PASSWORD"
  zulip__jwt_auth_key:
    environment: "ZULIP__JWT_AUTH_KEY"

networks:
  default:
    internal: true
    name: valle-zulip-internal
  supabase_default:
    external: true
